### ISSUE TITLE
Generacion de Código QR Según nueva normativa de AFIP

### ISSUE THREAD

**Issue by aledc7** [neocomplexx/neopdf#1]
Hola estimados, quisiera saber si ya existe algún desarrollo relacionado al nuevo requerimiento de AFIP para incluir un código QR en el pie de las facturas electrónicas.  
 Este es el link de la documentación oficial: 
[https://www.afip.gob.ar/fe/qr/conceptos-generales.asp](https://www.afip.gob.ar/fe/qr/conceptos-generales.aspl)

En caso de que no exista nada desarrollado me gustaría contribuir con el desarrollo.

Saludos.

Ing. Alejandro De Castro

**Comment by aledc7** [comment]
ya he desarrollado la integración del código QR de AFIP, si les parece puedo subir el ejemplo funcionando que tengo.

**Comment by froston** [comment]
Hola @aledc7, 
Podrías crear un PR con el update?
Muchas gracias!

**Comment by martindeleo** [comment]
Hola ! Saben como poder imprimir en una impresora térmica ? Genero mi factura con QR usando crystal report en hoja A4, pero no se como resolver la impresión en una impresora térmica. Controlo el ancho de la hoja de 8 cm... pero no resuelvo el corte de linea ni el largo.
